FROM golang:1.20-buster as builder

WORKDIR /opt

ENV GOPATH /go
ENV PATH /go/bin:$PATH

RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin

COPY . /opt/bridge
RUN cd bridge && make bridge

FROM debian:buster

RUN apt-get update  && apt-get install -y --no-install-recommends ca-certificates
RUN update-ca-certificates

WORKDIR "/opt"

ENV CONFIG_PATH ''
ENV VERBOSITY 3
ENV NUMBEROFWORKERS 1024

ENV LISTENERS__RONIN__CONFIG__RPCURL ''
ENV LISTENERS__RONIN__CONFIG__SECRET__BRIDGEOPERATOR__PLAINPRIVATEKEY ''
ENV LISTENERS__RONIN__CONFIG__TASKINTERVAL ''
ENV LISTENERS__RONIN__CONFIG__TRANSACTIONCHECKPERIOD ''
ENV LISTENERS__RONIN__CONFIG__FROMHEIGHT ''
ENV LISTENERS__RONIN__CONFIG__GASLIMITBUMPRATIO ''

ENV LISTENERS__RONIN__CONFIG__MAXTASKQUERY ''
ENV LISTENERS__RONIN__CONFIG__MAXPROCESSINGTASKS ''

ENV LISTENERS__RONIN__STATS__NODE ''
ENV LISTENERS__RONIN__STATS__HOST ''
ENV LISTENERS__RONIN__STATS__SECRET ''

ENV LISTENERS__ETHEREUM__CONFIG__RPCURL ''
ENV LISTENERS__ETHEREUM__CONFIG__SECRET__BRIDGEOPERATOR__PLAINPRIVATEKEY ''
ENV LISTENERS__ETHEREUM__CONFIG__GETLOGSBATCHSIZE ''

ENV DATABASE__HOST ''
ENV DATABASE__PORT ''
ENV DATABASE__NAME ''
ENV DATABASE__USERNAME ''
ENV DATABASE__PASSWORD ''
ENV DATABASE__CONNMAXLIFETIME ''
ENV DATABASE__MAXIDLECONNS ''
ENV DATABASE__MAXOPENCONNS ''

COPY --from=builder /go/bin/bridge /usr/local/bin/bridge
COPY --from=builder /opt/bridge/config/ ./
COPY --from=builder /opt/bridge/docker/entrypoint.sh ./

ENTRYPOINT ["./entrypoint.sh"]
